name: bmi_calculator_app
description: "A BMI Calculator App for mobile programming project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸŒ Há»— trá»£ Ä‘a ngÃ´n ngá»¯
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # ðŸ“Š Biá»ƒu Ä‘á»“ BMI
  fl_chart: ^1.1.1

  # ðŸ’¾ LÆ°u dá»¯ liá»‡u cá»¥c bá»™
  shared_preferences: ^2.3.2

  # ðŸ“¤ Chia sáº» káº¿t quáº£ BMI
  share_plus: ^12.0.1

  # ðŸ”¥ Firebase
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/home.jpg
    - assets/images/logo.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

# ðŸŒ Äáº·t cáº¥u hÃ¬nh l10n á»Ÿ ngoÃ i má»¥c "flutter"
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
